def FAMILY_SLIME     equ $00
def FAMILY_DRAGON    equ $01
def FAMILY_BEAST     equ $02
def FAMILY_BIRD      equ $03
def FAMILY_PLANT     equ $04
def FAMILY_BUG       equ $05
def FAMILY_DEVIL     equ $06
def FAMILY_ZOMBIE    equ $07
def FAMILY_MATERIAL  equ $08
def FAMILY_BOSS      equ $09
