def GATE_BEGINNING      equ $00
def GATE_VILLAGER       equ $01
def GATE_TALISMAN       equ $02
def GATE_MEMORIES       equ $03
def GATE_BEWILDER       equ $04
def GATE_BAZAAR_1       equ $05
def GATE_PEACE          equ $06
def GATE_BRAVERY        equ $07
def GATE_WELL           equ $08
def GATE_STRENGTH       equ $09
def GATE_ANGER          equ $0A
def GATE_MONSTER_FARM   equ $0B
def GATE_JOY            equ $0C
def GATE_WISDOM         equ $0D
def GATE_ARENA_LEFT     equ $0E
def GATE_HAPPINESS      equ $0F
def GATE_TEMPTATION     equ $10
def GATE_MEDAL_MAN      equ $11
def GATE_LABYRINTH      equ $12
def GATE_JUDGMENT       equ $13
def GATE_LIBRARY        equ $14
def GATE_REFLECTION     equ $15
def GATE_AMBITION       equ $16
def GATE_DEMOLITION     equ $17
def GATE_MASTERMIND     equ $18
def GATE_CONTROL        equ $19
def GATE_EXTINCTION     equ $1A
def GATE_SLEEP          equ $1B
def GATE_BAZAAR_2       equ $1C
def GATE_ARENA_RIGHT    equ $1D
def GATE_OLD_MAN        equ $1E
def GATE_UNUSED_0x1F    equ $1F
