def ITEM_HERB          equ $01
def ITEM_LOVEWATER     equ $02
def ITEM_SAGE_STONE    equ $03
def ITEM_WORLD_DEW     equ $04
def ITEM_POTION        equ $05
def ITEM_ELF_WATER     equ $06
def ITEM_ANTIDOTE      equ $07
def ITEM_MOON_HERB     equ $08
def ITEM_SKY_BELL      equ $09
def ITEM_LAUREL        equ $0A
def ITEM_AWAKE_SAND    equ $0B
def ITEM_WORLD_LEAF    equ $0C
def ITEM_LIFE_ACORN    equ $0D
def ITEM_MYSTIC_NUT    equ $0E
def ITEM_ATK_SEED      equ $0F
def ITEM_DEF_SEED      equ $10
def ITEM_AGL_SEED      equ $11
def ITEM_INT_SEED      equ $12
def ITEM_BEEF_JERKY    equ $13
def ITEM_PORK_CHOP     equ $14
def ITEM_RIB           equ $15
def ITEM_BAD_MEAT      equ $16
def ITEM_SIRLOIN       equ $17
def ITEM_BOLT_STAFF    equ $18
def ITEM_WIND_STAFF    equ $19
def ITEM_MIST_STAFF    equ $1A
def ITEM_LAVA_STAFF    equ $1B
def ITEM_SNOW_STAFF    equ $1C
def ITEM_WARP_WING     equ $1D
def ITEM_TINY_MEDAL    equ $1E
def ITEM_QUEST_BOOK    equ $1F
def ITEM_HORROR_BOOK   equ $20
def ITEM_BE_NICE_BOOK  equ $21
def ITEM_CHEATER_BOOK  equ $22
def ITEM_SMART_BOOK    equ $23
def ITEM_COMEDY_BOOK   equ $24
def ITEM_FIRE_STAFF    equ $25
def ITEM_BEAST_TAIL    equ $26
def ITEM_WARP_STAFF    equ $27
def ITEM_REPELLENT     equ $28
def ITEM_SHINY_HARP    equ $29
def ITEM_MAP_HERB      equ $2A
def ITEM_BOOKMARK      equ $2B
