def MONSTER_DRAKSLIME     equ $00
def MONSTER_SPOTSLIME     equ $01
def MONSTER_WINGSLIME     equ $02
def MONSTER_TREESLIME     equ $03
def MONSTER_SNAILY        equ $04
def MONSTER_SLIMENITE     equ $05
def MONSTER_BABBLE        equ $06
def MONSTER_BOXSLIME      equ $07
def MONSTER_SLIME         equ $08
def MONSTER_HEALER        equ $09
def MONSTER_FANGSLIME     equ $0A
def MONSTER_ROCKSLIME     equ $0B
def MONSTER_SLIMEBORG     equ $0C
def MONSTER_SLABBIT       equ $0D
def MONSTER_SPOTKING      equ $0E
def MONSTER_KINGSLIME     equ $0F
def MONSTER_METALY        equ $10
def MONSTER_METABBLE      equ $11
def MONSTER_METALKING     equ $12
def MONSTER_GOLDSLIME     equ $13
def MONSTER_DRAGONKID     equ $14
def MONSTER_TOTRAGON      equ $15
def MONSTER_PTERANOD      equ $16
def MONSTER_GASGON        equ $17
def MONSTER_FAIRYDRAK     equ $18
def MONSTER_LIZARDMAN     equ $19
def MONSTER_POISONGON     equ $1A
def MONSTER_SWORDGON      equ $1B
def MONSTER_DRAGON        equ $1C
def MONSTER_MINIDRAK      equ $1D
def MONSTER_MADDRAGON     equ $1E
def MONSTER_RAYBURN       equ $1F
def MONSTER_CHAMELGON     equ $20
def MONSTER_LIZARDFLY     equ $21
def MONSTER_ANDREAL       equ $22
def MONSTER_KINGCOBRA     equ $23
def MONSTER_SPIKEROUS     equ $24
def MONSTER_GREATDRAK     equ $25
def MONSTER_CRESTPENT     equ $26
def MONSTER_WINGSNAKE     equ $27
def MONSTER_COATOL        equ $28
def MONSTER_OROCHI        equ $29
def MONSTER_BATTLEREX     equ $2A
def MONSTER_SKYDRAGON     equ $2B
def MONSTER_DIVINEGON     equ $2C
def MONSTER_TONGUELLA     equ $2D
def MONSTER_ALMIRAJ       equ $2E
def MONSTER_CATFLY        equ $2F
def MONSTER_PILLOWRAT     equ $30
def MONSTER_SACCER        equ $31
def MONSTER_GULPBEAST     equ $32
def MONSTER_SKULLROO      equ $33
def MONSTER_WINDBEAST     equ $34
def MONSTER_ANTEATER      equ $35
def MONSTER_SUPERTEN      equ $36
def MONSTER_IRONTURT      equ $37
def MONSTER_MOMMONJA      equ $38
def MONSTER_HAMMERMAN     equ $39
def MONSTER_GRIZZLY       equ $3A
def MONSTER_YETI          equ $3B
def MONSTER_MADGOPHER     equ $3C
def MONSTER_FAIRYRAT      equ $3D
def MONSTER_UNICORN       equ $3E
def MONSTER_GOATEGON      equ $3F
def MONSTER_WILDAPE       equ $40
def MONSTER_TRUMPETER     equ $41
def MONSTER_KINGLEO       equ $42
def MONSTER_DARKHORN      equ $43
def MONSTER_MADCAT        equ $44
def MONSTER_BIGEYE        equ $45
def MONSTER_PICKY         equ $46
def MONSTER_WYVERN        equ $47
def MONSTER_BULLBIRD      equ $48
def MONSTER_FLORAJAY      equ $49
def MONSTER_DUCKKITE      equ $4A
def MONSTER_MADPECKER     equ $4B
def MONSTER_MADRAVEN      equ $4C
def MONSTER_MISTYWING     equ $4D
def MONSTER_DRACKY        equ $4E
def MONSTER_BIGROOST      equ $4F
def MONSTER_STUBBIRD      equ $50
def MONSTER_LANDOWL       equ $51
def MONSTER_MADGOOSE      equ $52
def MONSTER_MADCONDOR     equ $53
def MONSTER_BLIZZARDY     equ $54
def MONSTER_PHOENIX       equ $55
def MONSTER_ZAPBIRD       equ $56
def MONSTER_WHIPBIRD      equ $57
def MONSTER_FUNKYBIRD     equ $58
def MONSTER_RAINHAWK      equ $59
def MONSTER_MADPLANT      equ $5A
def MONSTER_FIREWEED      equ $5B
def MONSTER_FLORAMAN      equ $5C
def MONSTER_WINGTREE      equ $5D
def MONSTER_CACTIBALL     equ $5E
def MONSTER_GULPPE        equ $5F
def MONSTER_TOADSTOOL     equ $60
def MONSTER_AMBERWEED     equ $61
def MONSTER_STUBSTUCK     equ $62
def MONSTER_ONIONO        equ $63
def MONSTER_DANCEVEGI     equ $64
def MONSTER_TREEBOY       equ $65
def MONSTER_FACETREE      equ $66
def MONSTER_HERBMAN       equ $67
def MONSTER_BEANMAN       equ $68
def MONSTER_EVILSEED      equ $69
def MONSTER_MANEATER      equ $6A
def MONSTER_SNAPPER       equ $6B
def MONSTER_ROSEVINE      equ $6C
def MONSTER_WATABOU       equ $6D
def MONSTER_GIANTSLUG     equ $6E
def MONSTER_CATAPILA      equ $6F
def MONSTER_GOPHECADA     equ $70
def MONSTER_BUTTERFLY     equ $71
def MONSTER_WEEDBUG       equ $72
def MONSTER_GIANTWORM     equ $73
def MONSTER_LIPSY         equ $74
def MONSTER_STAGBUG       equ $75
def MONSTER_ARMYANT       equ $76
def MONSTER_GOHOPPER      equ $77
def MONSTER_TAILEATER     equ $78
def MONSTER_ARMORPEDE     equ $79
def MONSTER_EYEDER        equ $7A
def MONSTER_GIANTMOTH     equ $7B
def MONSTER_DROLL         equ $7C
def MONSTER_ARMYCRAB      equ $7D
def MONSTER_MADHORNET     equ $7E
def MONSTER_HORNBEET      equ $7F
def MONSTER_ARMORPION     equ $80
def MONSTER_DIGSTER       equ $81
def MONSTER_PIXY          equ $82
def MONSTER_ARCDEMON      equ $83
def MONSTER_AGDEVIL       equ $84
def MONSTER_DEMONITE      equ $85
def MONSTER_DARKEYE       equ $86
def MONSTER_EYEBALL       equ $87
def MONSTER_SKULRIDER     equ $88
def MONSTER_EVILBEAST     equ $89
def MONSTER_1EYECLOWN     equ $8A
def MONSTER_GREMLIN       equ $8B
def MONSTER_MEDUSAEYE     equ $8C
def MONSTER_LIONEX        equ $8D
def MONSTER_GOATHORN      equ $8E
def MONSTER_ORC           equ $8F
def MONSTER_OGRE          equ $90
def MONSTER_GATEGUARD     equ $91
def MONSTER_CHOPCLOWN     equ $92
def MONSTER_GRENDAL       equ $93
def MONSTER_AKUBAR        equ $94
def MONSTER_MADKNIGHT     equ $95
def MONSTER_GIGANTES      equ $96
def MONSTER_CENTASAUR     equ $97
def MONSTER_EVILARMOR     equ $98
def MONSTER_JAMIRUS       equ $99
def MONSTER_DURRAN        equ $9A
def MONSTER_SPOOKY        equ $9B
def MONSTER_SKULLGON      equ $9C
def MONSTER_PUTREPUP      equ $9D
def MONSTER_ROTRAVEN      equ $9E
def MONSTER_MUMMY         equ $9F
def MONSTER_DARKCRAB      equ $A0
def MONSTER_DEADNITE      equ $A1
def MONSTER_SHADOW        equ $A2
def MONSTER_HORK          equ $A3
def MONSTER_MUDRON        equ $A4
def MONSTER_NITEWHIP      equ $A5
def MONSTER_MADSPIRIT     equ $A6
def MONSTER_WINDMERGE     equ $A7
def MONSTER_REAPER        equ $A8
def MONSTER_DEADNOBLE     equ $A9
def MONSTER_WHITEKING     equ $AA
def MONSTER_BONESLAVE     equ $AB
def MONSTER_SKELETOR      equ $AC
def MONSTER_SERVANT       equ $AD
def MONSTER_COPYCAT       equ $AE
def MONSTER_JEWELBAG      equ $AF
def MONSTER_EVILWAND      equ $B0
def MONSTER_MADCANDLE     equ $B1
def MONSTER_COILBIRD      equ $B2
def MONSTER_FACER         equ $B3
def MONSTER_SPIKYBOY      equ $B4
def MONSTER_MADMIRROR     equ $B5
def MONSTER_ROGUENITE     equ $B6
def MONSTER_GOOPI         equ $B7
def MONSTER_VOODOLL       equ $B8
def MONSTER_METALDRAK     equ $B9
def MONSTER_BALZAK        equ $BA
def MONSTER_SABREMAN      equ $BB
def MONSTER_CURSELAMP     equ $BC
def MONSTER_ROBOSTER      equ $BD
def MONSTER_EVILPOT       equ $BE
def MONSTER_GISMO         equ $BF
def MONSTER_LAVAMAN       equ $C0
def MONSTER_ICEMAN        equ $C1
def MONSTER_MIMIC         equ $C2
def MONSTER_MUDDOLL       equ $C3
def MONSTER_GOLEM         equ $C4
def MONSTER_STONEMAN      equ $C5
def MONSTER_BOMBCRAG      equ $C6
def MONSTER_GOLDGOLEM     equ $C7
def MONSTER_DRACOLORD1    equ $C8
def MONSTER_DRACOLORD2    equ $C9
def MONSTER_HARGON        equ $CA
def MONSTER_SIDOH         equ $CB
def MONSTER_BARAMOS       equ $CC
def MONSTER_ZOMA          equ $CD
def MONSTER_PIZZARO       equ $CE
def MONSTER_ESTERK        equ $CF
def MONSTER_MIRUDRAAS1    equ $D0
def MONSTER_MIRUDRAAS2    equ $D1
def MONSTER_MUDOU         equ $D2
def MONSTER_DEATHMORE1    equ $D3
def MONSTER_DEATHMORE2    equ $D4
def MONSTER_DEATHMORE3    equ $D5
def MONSTER_DARKDRIUM     equ $D6
