def SKILL_BLAZE         equ $00
def SKILL_BLAZEMORE     equ $01
def SKILL_BLAZEMOST     equ $02
def SKILL_FIREBAL       equ $03
def SKILL_FIREBANE      equ $04
def SKILL_FIREBOLT      equ $05
def SKILL_BANG          equ $06
def SKILL_BOOM          equ $07
def SKILL_EXPLODET      equ $08
def SKILL_INFERNOS      equ $09
def SKILL_INFERMORE     equ $0A
def SKILL_INFERMOST     equ $0B
def SKILL_ICEBOLT       equ $0C
def SKILL_SNOWSTORM     equ $0D
def SKILL_BLIZZARD      equ $0E
def SKILL_BOLT          equ $0F
def SKILL_ZAP           equ $10
def SKILL_THORDAIN      equ $11
def SKILL_BEAT          equ $12
def SKILL_DEFEAT        equ $13
def SKILL_SACRIFICE     equ $14
def SKILL_SLEEP         equ $15
def SKILL_SLEEPALL      equ $16
def SKILL_STOPSPELL     equ $17
def SKILL_SURROUND      equ $18
def SKILL_PANICALL      equ $19
def SKILL_ROBMAGIC      equ $1A
def SKILL_TAKEMAGIC     equ $1B
def SKILL_SAP           equ $1C
def SKILL_DEFENCE       equ $1D
def SKILL_UPPER         equ $1E
def SKILL_INCREASE      equ $1F
def SKILL_SLOW          equ $20
def SKILL_SLOWALL       equ $21
def SKILL_SPEED         equ $22
def SKILL_SPEEDUP       equ $23
def SKILL_BARRIER       equ $24
def SKILL_TWINHITS      equ $25
def SKILL_MAGICWALL     equ $26
def SKILL_MAGICBACK     equ $27
def SKILL_BOUNCE        equ $28
def SKILL_TRANSFORM     equ $29
def SKILL_IRONIZE       equ $2A
def SKILL_HEAL          equ $2B
def SKILL_HEALMORE      equ $2C
def SKILL_HEALALL       equ $2D
def SKILL_HEALUS        equ $2E
def SKILL_HEALUSALL     equ $2F
def SKILL_VIVIFY        equ $30
def SKILL_REVIVE        equ $31
def SKILL_FAREWELL      equ $32
def SKILL_ANTIDOTE      equ $33
def SKILL_NUMBOFF       equ $34
def SKILL_DECHAOS       equ $35
def SKILL_CURSEOFF      equ $36
def SKILL_STEPGUARD     equ $37
def SKILL_MAPMAGIC      equ $38
def SKILL_CHANCE        equ $39
def SKILL_UNUSED_3A     equ $3A
def SKILL_TWINSLASH     equ $3B
def SKILL_RAMMING       equ $3C
def SKILL_BESERKER      equ $3D
def SKILL_KAMIKAZE      equ $3E
def SKILL_MASSACRE      equ $3F
def SKILL_EVILSLASH     equ $40
def SKILL_CHARGEUP      equ $41
def SKILL_HIGHJUMP      equ $42
def SKILL_SUCKAIR       equ $43
def SKILL_FIRESLASH     equ $44
def SKILL_BOLTSLASH     equ $45
def SKILL_VACUSLASH     equ $46
def SKILL_ICESLASH      equ $47
def SKILL_METALCUT      equ $48
def SKILL_DRAGONCUT     equ $49
def SKILL_BEASTCUT      equ $4A
def SKILL_BIRDBLOW      equ $4B
def SKILL_DEVILCUT      equ $4C
def SKILL_ZOMBIECUT     equ $4D
def SKILL_CLEANCUT      equ $4E
def SKILL_MULTICUT      equ $4F
def SKILL_BIATTACK      equ $50
def SKILL_QUADHITS      equ $51
def SKILL_CALLHELP      equ $52
def SKILL_YELLHELP      equ $53
def SKILL_FOCUS         equ $54
def SKILL_SQUALLHIT     equ $55
def SKILL_PSYCHEUP      equ $56
def SKILL_RAINSLASH     equ $57
def SKILL_WINDBEAST     equ $58
def SKILL_VACUUM        equ $59
def SKILL_LIGHTNING     equ $5A
def SKILL_ROCKTHROW     equ $5B
def SKILL_FIREAIR       equ $5C
def SKILL_BLAZEAIR      equ $5D
def SKILL_SCORCHING     equ $5E
def SKILL_WHITEFIRE     equ $5F
def SKILL_FRIGIDAIR     equ $60
def SKILL_ICEAIR        equ $61
def SKILL_ICESTORM      equ $62
def SKILL_WHITEAIR      equ $63
def SKILL_HELLBLAST     equ $64
def SKILL_BIGBANG       equ $65
def SKILL_MEGAMAGIC     equ $66
def SKILL_POISONHIT     equ $67
def SKILL_NAPATTACK     equ $68
def SKILL_PARALYZE      equ $69
def SKILL_SLEEPAIR      equ $6A
def SKILL_PALSYAIR      equ $6B
def SKILL_POISONGAS     equ $6C
def SKILL_POISONAIR     equ $6D
def SKILL_PANIDANCE     equ $6E
def SKILL_CURSE         equ $6F
def SKILL_AHHH          equ $70
def SKILL_KO_DANCE      equ $71
def SKILL_SANDSTORM     equ $72
def SKILL_RADIANT       equ $73
def SKILL_EERIELITE     equ $74
def SKILL_ODDDANCE      equ $75
def SKILL_ROBDANCE      equ $76
def SKILL_SIDESTEP      equ $77
def SKILL_LUREDANCE     equ $78
def SKILL_LUSHLICKS     equ $79
def SKILL_SICKLICK      equ $7A
def SKILL_LEGSWEEP      equ $7B
def SKILL_BIGTRIP       equ $7C
def SKILL_WARCRY        equ $7D
def SKILL_WHISTLE       equ $7E
def SKILL_IMITATE       equ $7F
def SKILL_DEMAGIC       equ $80
def SKILL_SURGE         equ $81
def SKILL_ULTRADOWN     equ $82
def SKILL_THICKFOG      equ $83
def SKILL_TATSUCALL     equ $84
def SKILL_DIAGOCALL     equ $85
def SKILL_SAMSICALL     equ $86
def SKILL_BAZOOCALL     equ $87
def SKILL_COVER         equ $88
def SKILL_GUARDIAN      equ $89
def SKILL_TAILWIND      equ $8A
def SKILL_STORMWIND     equ $8B
def SKILL_DODGE         equ $8C
def SKILL_UNUSED_8D     equ $8D
def SKILL_STRONGD       equ $8E
def SKILL_SUCKALL       equ $8F
def SKILL_BLADED        equ $90
def SKILL_DANCESHUT     equ $91
def SKILL_MOUTHSHUT     equ $92
def SKILL_MEDITATE      equ $93
def SKILL_HUSTLE        equ $94
def SKILL_LIFESONG      equ $95
def SKILL_LIFEDANCE     equ $96
def SKILL_BEDRAGON      equ $D5
def SKILL_SMASHLIME     equ $D6
def SKILL_DRAKSLASH     equ $D7
def SKILL_BRANCHING     equ $D8
def SKILL_GIGASLASH     equ $D9
def SKILL_NONE          equ $FF
