def SPECIES_DRAKSLIME     equ $00
def SPECIES_SPOTSLIME     equ $01
def SPECIES_WINGSLIME     equ $02
def SPECIES_TREESLIME     equ $03
def SPECIES_SNAILY        equ $04
def SPECIES_SLIMENITE     equ $05
def SPECIES_BABBLE        equ $06
def SPECIES_BOXSLIME      equ $07
def SPECIES_SLIME         equ $08
def SPECIES_HEALER        equ $09
def SPECIES_FANGSLIME     equ $0A
def SPECIES_ROCKSLIME     equ $0B
def SPECIES_SLIMEBORG     equ $0C
def SPECIES_SLABBIT       equ $0D
def SPECIES_SPOTKING      equ $0E
def SPECIES_KINGSLIME     equ $0F
def SPECIES_METALY        equ $10
def SPECIES_METABBLE      equ $11
def SPECIES_METALKING     equ $12
def SPECIES_GOLDSLIME     equ $13
def SPECIES_DRAGONKID     equ $14
def SPECIES_TORTRAGON     equ $15
def SPECIES_PTERANOD      equ $16
def SPECIES_GASGON        equ $17
def SPECIES_FAIRYDRAK     equ $18
def SPECIES_LIZARDMAN     equ $19
def SPECIES_POISONGON     equ $1A
def SPECIES_SWORDGON      equ $1B
def SPECIES_DRAGON        equ $1C
def SPECIES_MINIDRAK      equ $1D
def SPECIES_MADDRAGON     equ $1E
def SPECIES_RAYBURN       equ $1F
def SPECIES_CHAMELGON     equ $20
def SPECIES_LIZARDFLY     equ $21
def SPECIES_ANDREAL       equ $22
def SPECIES_KINGCOBRA     equ $23
def SPECIES_SPIKEROUS     equ $24
def SPECIES_GREATDRAK     equ $25
def SPECIES_CRESTPENT     equ $26
def SPECIES_WINGSNAKE     equ $27
def SPECIES_COATOL        equ $28
def SPECIES_OROCHI        equ $29
def SPECIES_BATTLEREX     equ $2A
def SPECIES_SKYDRAGON     equ $2B
def SPECIES_DIVINEGON     equ $2C
def SPECIES_TONGUELLA     equ $2D
def SPECIES_ALMIRAJ       equ $2E
def SPECIES_CATFLY        equ $2F
def SPECIES_PILLOWRAT     equ $30
def SPECIES_SACCER        equ $31
def SPECIES_GULPBEAST     equ $32
def SPECIES_SKULLROO      equ $33
def SPECIES_WINDBEAST     equ $34
def SPECIES_ANTEATER      equ $35
def SPECIES_SUPERTEN      equ $36
def SPECIES_IRONTURT      equ $37
def SPECIES_MOMMONJA      equ $38
def SPECIES_HAMMERMAN     equ $39
def SPECIES_GRIZZLY       equ $3A
def SPECIES_YETI          equ $3B
def SPECIES_MADGOPHER     equ $3C
def SPECIES_FAIRYRAT      equ $3D
def SPECIES_UNICORN       equ $3E
def SPECIES_GOATEGON      equ $3F
def SPECIES_WILDAPE       equ $40
def SPECIES_TRUMPETER     equ $41
def SPECIES_KINGLEO       equ $42
def SPECIES_DARKHORN      equ $43
def SPECIES_MADCAT        equ $44
def SPECIES_BIGEYE        equ $45
def SPECIES_PICKY         equ $46
def SPECIES_WYVERN        equ $47
def SPECIES_BULLBIRD      equ $48
def SPECIES_FLORAJAY      equ $49
def SPECIES_DUCKKITE      equ $4A
def SPECIES_MADPECKER     equ $4B
def SPECIES_MADRAVEN      equ $4C
def SPECIES_MISTYWING     equ $4D
def SPECIES_DRACKY        equ $4E
def SPECIES_BIGROOST      equ $4F
def SPECIES_STUBBIRD      equ $50
def SPECIES_LANDOWL       equ $51
def SPECIES_MADGOOSE      equ $52
def SPECIES_MADCONDOR     equ $53
def SPECIES_BLIZZARDY     equ $54
def SPECIES_PHOENIX       equ $55
def SPECIES_ZAPBIRD       equ $56
def SPECIES_WHIPBIRD      equ $57
def SPECIES_FUNKYBIRD     equ $58
def SPECIES_RAINHAWK      equ $59
def SPECIES_MADPLANT      equ $5A
def SPECIES_FIREWEED      equ $5B
def SPECIES_FLORAMAN      equ $5C
def SPECIES_WINGTREE      equ $5D
def SPECIES_CACTIBALL     equ $5E
def SPECIES_GULPPLE       equ $5F
def SPECIES_TOADSTOOL     equ $60
def SPECIES_AMBERWEED     equ $61
def SPECIES_STUBSUCK      equ $62
def SPECIES_ONIONO        equ $63
def SPECIES_DANCEVEGI     equ $64
def SPECIES_TREEBOY       equ $65
def SPECIES_FACETREE      equ $66
def SPECIES_HERBMAN       equ $67
def SPECIES_BEANMAN       equ $68
def SPECIES_EVILSEED      equ $69
def SPECIES_MANEATER      equ $6A
def SPECIES_SNAPPER       equ $6B
def SPECIES_ROSEVINE      equ $6C
def SPECIES_WATABOU       equ $6D
def SPECIES_GIANTSLUG     equ $6E
def SPECIES_CATAPILA      equ $6F
def SPECIES_GOPHECADA     equ $70
def SPECIES_BUTTERFLY     equ $71
def SPECIES_WEEDBUG       equ $72
def SPECIES_GIANTWORM     equ $73
def SPECIES_LIPSY         equ $74
def SPECIES_STAGBUG       equ $75
def SPECIES_ARMYANT       equ $76
def SPECIES_GOHOPPER      equ $77
def SPECIES_TAILEATER     equ $78
def SPECIES_ARMORPEDE     equ $79
def SPECIES_EYEDER        equ $7A
def SPECIES_GIANTMOTH     equ $7B
def SPECIES_DROLL         equ $7C
def SPECIES_ARMYCRAB      equ $7D
def SPECIES_MADHORNET     equ $7E
def SPECIES_HORNBEET      equ $7F
def SPECIES_ARMORPION     equ $80
def SPECIES_DIGSTER       equ $81
def SPECIES_PIXY          equ $82
def SPECIES_ARCDEMON      equ $83
def SPECIES_AGDEVIL       equ $84
def SPECIES_DEMONITE      equ $85
def SPECIES_DARKEYE       equ $86
def SPECIES_EYEBALL       equ $87
def SPECIES_SKULRIDER     equ $88
def SPECIES_EVILBEAST     equ $89
def SPECIES_1EYECLOWN     equ $8A
def SPECIES_GREMLIN       equ $8B
def SPECIES_MEDUSAEYE     equ $8C
def SPECIES_LIONEX        equ $8D
def SPECIES_GOATHORN      equ $8E
def SPECIES_ORC           equ $8F
def SPECIES_OGRE          equ $90
def SPECIES_GATEGUARD     equ $91
def SPECIES_CHOPCLOWN     equ $92
def SPECIES_GRENDAL       equ $93
def SPECIES_AKUBAR        equ $94
def SPECIES_MADKNIGHT     equ $95
def SPECIES_GIGANTES      equ $96
def SPECIES_CENTASAUR     equ $97
def SPECIES_EVILARMOR     equ $98
def SPECIES_JAMIRUS       equ $99
def SPECIES_DURRAN        equ $9A
def SPECIES_SPOOKY        equ $9B
def SPECIES_SKULLGON      equ $9C
def SPECIES_PUTREPUP      equ $9D
def SPECIES_ROTRAVEN      equ $9E
def SPECIES_MUMMY         equ $9F
def SPECIES_DARKCRAB      equ $A0
def SPECIES_DEADNITE      equ $A1
def SPECIES_SHADOW        equ $A2
def SPECIES_HORK          equ $A3
def SPECIES_MUDRON        equ $A4
def SPECIES_NITEWHIP      equ $A5
def SPECIES_MADSPIRIT     equ $A6
def SPECIES_WINDMERGE     equ $A7
def SPECIES_REAPER        equ $A8
def SPECIES_DEADNOBLE     equ $A9
def SPECIES_WHITEKING     equ $AA
def SPECIES_BONESLAVE     equ $AB
def SPECIES_SKELETOR      equ $AC
def SPECIES_SERVANT       equ $AD
def SPECIES_COPYCAT       equ $AE
def SPECIES_JEWELBAG      equ $AF
def SPECIES_EVILWAND      equ $B0
def SPECIES_MADCANDLE     equ $B1
def SPECIES_COILBIRD      equ $B2
def SPECIES_FACER         equ $B3
def SPECIES_SPIKYBOY      equ $B4
def SPECIES_MADMIRROR     equ $B5
def SPECIES_ROGUENITE     equ $B6
def SPECIES_GOOPI         equ $B7
def SPECIES_VOODOLL       equ $B8
def SPECIES_METALDRAK     equ $B9
def SPECIES_BALZAK        equ $BA
def SPECIES_SABREMAN      equ $BB
def SPECIES_CURSELAMP     equ $BC
def SPECIES_ROBOSTER      equ $BD
def SPECIES_EVILPOT       equ $BE
def SPECIES_GISMO         equ $BF
def SPECIES_LAVAMAN       equ $C0
def SPECIES_ICEMAN        equ $C1
def SPECIES_MIMIC         equ $C2
def SPECIES_MUDDOLL       equ $C3
def SPECIES_GOLEM         equ $C4
def SPECIES_STONEMAN      equ $C5
def SPECIES_BOMBCRAG      equ $C6
def SPECIES_GOLDGOLEM     equ $C7
def SPECIES_DRACOLORD1    equ $C8
def SPECIES_DRACOLORD2    equ $C9
def SPECIES_HARGON        equ $CA
def SPECIES_SIDOH         equ $CB
def SPECIES_BARAMOS       equ $CC
def SPECIES_ZOMA          equ $CD
def SPECIES_PIZZARO       equ $CE
def SPECIES_ESTERK        equ $CF
def SPECIES_MIRUDRAAS1    equ $D0
def SPECIES_MIRUDRAAS2    equ $D1
def SPECIES_MUDOU         equ $D2
def SPECIES_DEATHMORE1    equ $D3
def SPECIES_DEATHMORE2    equ $D4
def SPECIES_DEATHMORE3    equ $D5
def SPECIES_DARKDRIUM     equ $D6
