charmap "0",            $00
charmap "1",            $01
charmap "2",            $02
charmap "3",            $03
charmap "4",            $04
charmap "5",            $05
charmap "6",            $06
charmap "7",            $07
charmap "8",            $08
charmap "9",            $09

charmap "[SLIME]",      $10
charmap "[DRAGON]",     $11
charmap "[BEAST]",      $12
charmap "[BIRD]",       $13
charmap "[PLANT]",      $14
charmap "[BUG]",        $15
charmap "[DEVIL]",      $16
charmap "[ZOMBIE]",     $17
charmap "[MATERIAL]",   $18
charmap "[BOSS]",       $19

charmap "A",            $24
charmap "B",            $25
charmap "C",            $26
charmap "D",            $27
charmap "E",            $28
charmap "F",            $29
charmap "G",            $2A
charmap "H",            $2B
charmap "I",            $2C
charmap "J",            $2D
charmap "K",            $2E
charmap "L",            $2F
charmap "M",            $30
charmap "N",            $31
charmap "O",            $32
charmap "P",            $33
charmap "Q",            $34
charmap "R",            $35
charmap "S",            $36
charmap "T",            $37
charmap "U",            $38
charmap "V",            $39
charmap "W",            $3A
charmap "X",            $3B
charmap "Y",            $3C
charmap "Z",            $3D
charmap "a",            $3E
charmap "b",            $3F
charmap "c",            $40
charmap "d",            $41
charmap "e",            $42
charmap "f",            $43
charmap "g",            $44
charmap "h",            $45
charmap "i",            $46
charmap "j",            $47
charmap "k",            $48
charmap "l",            $49
charmap "m",            $4A
charmap "n",            $4B
charmap "o",            $4C
charmap "p",            $4D
charmap "q",            $4E
charmap "r",            $4F
charmap "s",            $50
charmap "t",            $51
charmap "u",            $52
charmap "v",            $53
charmap "w",            $54
charmap "x",            $55
charmap "y",            $56
charmap "z",            $57

charmap "'",            $5C
charmap "‣",            $5D
charmap ",",            $5E
charmap ".",            $5F
charmap ";",            $60
charmap "‥",            $61
charmap " ",            $62
charmap "!",            $63
charmap "?",            $64
charmap "\"",           $65
charmap "'l",           $66
charmap "'t",           $67
charmap "'s",           $68
charmap "'r",           $69
charmap "'m",           $6A
charmap "'y",           $6B
charmap "'v",           $6C
charmap "'d",           $6D
charmap "'e",           $6E
charmap "'c",           $6F
charmap "'n",           $70
charmap "'T",           $71

charmap "○",            $8F

charmap "[",            $96
charmap "]",            $97
charmap "?",            $98
charmap "!",            $99

charmap "•",            $9B
charmap "-",            $9C
charmap "~",            $9D
charmap "/",            $9E
charmap "*",            $9F
charmap "(",            $A0
charmap ")",            $A1
charmap "+",            $A2
charmap ":",            $A3
charmap "…",            $A4
charmap "<LV>",         $A5
charmap "<EX>",         $A6
charmap "♂",           $A7
charmap "♀",           $A8
charmap "↑",            $A9
charmap "★",           $AC
charmap "↓",            $AD
charmap "←",            $AE
charmap "→",            $AF
charmap "↖",            $B0
charmap "↗",            $B1
charmap "↙",            $B2
charmap "↘",            $B3
charmap "💤",           $B4
charmap "©",            $B5
charmap "&",            $B6

; default player name
charmap "ᴛ",            $D3
charmap "ᴇ",            $D4
charmap "ʀʀ",           $D5
charmap "ʏ",            $D6

charmap "<PLAYER>",     $F6
